---
title: LLM-Extraction Project - Baseline Characteristics Table
---

## Load packages
```{r}
#| echo: false
#| output: false
library(tidyverse)
library(REDCapR)
library(tinytable)
library(MedOnko)
```

## Load Data

```{r}
data <- redcap_read(
    redcap_uri = Sys.getenv("redcap_fxdb_url"),
    token = Sys.getenv("llm_radio_api"),
    raw_or_label = "label"
  )$data
```

## Use IDs to download baseline data

```{r}
imaging_data <- get_imaging_from_ier(data$ier_bk)

sex <- get_sex(imaging_data$PAT_BK)
birth_date <- get_birth(imaging_data$PAT_BK)

baseline_data <- imaging_data |> 
  left_join(birth_date, by = "PAT_BK") |>
  left_join(sex, by = "PAT_BK") |>
  mutate(
    age = as.numeric(difftime(IMAGING_DATE, PAT_BIRTH_DATE, units = "days"))/365.25
  ) |> 
  group_by(PAT_BK) |> 
  arrange(age) |> 
  slice_head(n = 1) |> 
  ungroup() |>
  select(age, sex = PAT_GENDER_ID) |> 
  distinct()

arrow::write_parquet(baseline_data, here::here("output", "oncology", "data", "baseline_data.parquet"))
```